# Generated by Django 4.0.4 on 2022-04-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='username',
        ),
    ]
