# Generated by Django 4.0.4 on 2022-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_business_remove_user_is_petlover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=11, null=True, unique=True),
        ),
    ]
