# Generated by Django 4.0.4 on 2022-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='height',
        ),
    ]
