# Generated by Django 4.0.4 on 2022-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='race',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
