# Generated by Django 4.0.4 on 2022-05-20 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptPet',
            fields=[
                ('pet_image', models.ImageField(null=True, upload_to='announcements/adopt')),
                ('title', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('info', models.TextField(max_length=750, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoundedPet',
            fields=[
                ('pet_image', models.ImageField(null=True, upload_to='announcements/founded')),
                ('title', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('info', models.TextField(max_length=750, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('pet_image', models.ImageField(null=True, upload_to='announcements/lost')),
                ('title', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('info', models.TextField(max_length=750, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
