# Generated by Django 4.0.4 on 2022-05-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_adoptpet_status_foundedpet_status_lostpet_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptpet',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='foundedpet',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='lostpet',
            options={'ordering': ['-created']},
        ),
    ]
